### PR TITLE
Pushing in PostgreSQL support & Username changes

### PR DESCRIPTION
**Pull request by hack13**

### CODE REVIEW

**Comment by JeffCost** [comment]
This is a good addition, I can accept the pull, but can you send only commit  [ab5f7ad](https://github.com/hack13/mwi/commit/ab5f7ad81ce5df2169d5079c4a9303aa73dc5d49) and targeted to the develop branch so it can be released with the next release version.

**Comment by hack13** [comment]
So you don't want to pull in the prostgresql support?

**Comment by JeffCost** [comment]
I can see you did changes on it, but you reverted back. no? Looking at the commits everything that you changed you reverted back. Am I missing something?

**Comment by hack13** [comment]
Yes I reverted back to proper case changes. We simply fixed the PostgreSQL module for opensim to do the ignore case requests. Although the more I think about it, we might have to just release a seperate version for postgresql, simply because it uses ILIKE instead of LIKE

**Comment by JeffCost** [comment]
Ok. I will take a look again as soon I get more time, in all the db queries in the application. For sure I will have to be updating more places through the app to make it compatible.

**Pull request closed without merging**
